DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

all: mqtt-demo
# Nuevo: 
#RPL_CONF_LEAF_ONLY = 1
#CONTIKI_WITH_RPL = 0
#

CONTIKI_WITH_IPV6 = 1

APPS += mqtt

CONTIKI=../../contiki
include $(CONTIKI)/Makefile.include

